dependencies = {
	layers: [
		{
			name: "compress.js",
			layerDependencies: [
			],
			dependencies: [
				"dijit.form.Button",
				"dijit.form.TextBox",
				"dijit.form.Form",
				"dijit.layout.ContentPane",
				"dijit.form.DateTextBox",
				"dijit.form.NumberTextBox",
				"dijit.form.ComboBox",
				"dijit.Toolbar",
				"dijit.Menu",
				"dijit.Dialog",

		 	    "dojo._base.unload",
		 	    "dojox.layout.ContentPane",
		 		"dijit.layout.BorderContainer",
		 		"dojox.layout.ToggleSplitter",
		 		"dojo._base.connect",

		 		"dojo._base.declare",
		 		"dijit.tree.ForestStoreModel",
		 		"dojo._base.lang",
		 		"dojo.data.ItemFileWriteStore",
		 		"dijit.layout.ContentPane",

		 		"dojox.grid.EnhancedGrid",
		 		"dojox.grid._RadioSelector",

		 		"dojo._base.declare",
		 		"dojo._base.lang",
		 		"dojo._base.connect",
		 		"dijit.Toolbar",
		 		"dijit.form.Button",
		 		"dijit.Tooltip",
		 		"dijit.layout.ContentPane",

		 		"dojo._base.connect",
		 		"dojo._base.declare",
		 		"dojo._base.lang",
		 		"dijit.form.Button",
		 		"dijit.form.DateTextBox",
		 		"dijit.form.SimpleTextarea",
		 		"dijit.form.NumberSpinner",
		 		"dijit.form.Select",

		 		"dojo._base.connect",
		 		"dojo._base.declare",
		 		"dijit.form.NumberSpinner",
		 		"dijit.form.Select",

		 		"dojo._base.declare",
		 		"dojo.data.ItemFileReadStore",
		 		"dojo._base.connect",
		 		"dojo.data.ItemFileWriteStore",
		 		"dojox.grid.EnhancedGrid",
		 		"dojo._base.lang",
		 		"dijit.layout.ContentPane",
		 		"dojox.grid._RadioSelector",

		 		"dojo._base.declare",
		 		"dojo._base.lang",
		 		"dojo._base.connect",
		 		"dijit.form.Button",
		 		"dijit.Tooltip",
		 		"dijit.ToolbarSeparator",

		 		"dojo._base.declare",
		 		"dojo._base.lang",
		 		"dojo._base.connect",
		 		"dijit.Toolbar",
		 		"dijit.form.Button",
		 		"dijit.Tooltip",
		 		"dijit.ToolbarSeparator",
		 		"dijit.layout.ContentPane",
		 		"dijit.form.Form",
		 		"dijit.form.ValidationTextBox",

		 		"dojo._base.declare",
		 		"dojo._base.connect",
		 		"dojo.data.ItemFileWriteStore",
		 		"dojox.grid.EnhancedGrid",
		 		"dojo._base.lang",
		 		"dijit.layout.ContentPane",

		 		"dijit.Tree",
		 		"dijit.form.ToggleButton",
		 		"dijit.form.CheckBox",
		 		"dojox.grid.enhanced.nls.Pagination",
		 		"dojox.data.QueryReadStore",
		 		"dojox.grid._CheckBoxSelector",

		 		"dojox.grid.enhanced._Plugin",
		 		"dijit._WidgetsInTemplateMixin",
		 		"dijit.form.RadioButton",
		 		"dojox.grid.enhanced.plugins.Dialog",
		 		"dojox.grid.enhanced.plugins._StoreLayer",
		 		"dojox.grid.enhanced._Plugin",

		 		"dojox.grid.enhanced.plugins.Pagination",
		 		"dijit.form.ComboButton",
		 		"dojox.grid.TreeGrid",
		 		"dojox.grid.TreeSelection",
		 		"dojox.grid.cells.tree",
		 		"dojox.grid._TreeView",

		 		"dijit.Tree",
		 		"dojo.DeferredList",
		 		"dojo.fx",
		 		"dijit.tree._dndSelector",
		 		"dijit.tree._dndContainer",
		 		"dojo.fx.Toggler",
		 		"dijit.layout.AccordionContainer",
		 		"dijit.focus",
		 		"dojo.Stateful",
		 		"dojo.window",
		 		"dijit.a11y",
		 		"dijit._base.manager",
		 		"dijit.registry",
		 		"dijit.main",
		 		"dijit._Widget",
		 		"dijit._WidgetBase",
		 		"dijit._OnDijitClickMixin",
		 		"dijit._FocusMixin",
		 		"dojo.uacss",
		 		"dijit.hccss",
		 		"dijit._Container",
		 		"dijit._TemplatedMixin",
		 		"dojo.touch",
		 		"dojo.string",
		 		"dojo.cache",
		 		"dijit._CssStateMixin",
		 		"dijit.layout.StackContainer",
		 		"dojo.cookie",
		 		"dojo.regexp",
		 		"dijit.layout._LayoutWidget",
		 		"dijit._Contained",
		 		"dijit.nls.common",
		 		"dijit.layout.ContentPane",
		 		"dijit.layout._ContentPaneResizeMixin",
		 		"dijit.layout.utils",
		 		"dojo.html",
		 		"dojo.parser",
		 		"dojo._base.url",
		 		"dojo.date.stamp",
		 		"dijit.nls.loading",
		 		"dijit._base",
		 		"dijit.WidgetSet",
		 		"dijit._base.focus",
		 		"dijit._base.place",
		 		"dijit.place",
		 		"dijit._base.popup",
		 		"dijit.popup",
		 		"dijit.BackgroundIframe",
		 		"dijit._base.scroll",
		 		"dijit._base.sniff",
		 		"dijit._base.typematic",
		 		"dijit.typematic",
		 		"dijit._base.wai",
		 		"dijit._base.window",
		 		"dijit.layout.StackController",
		 		"dijit.form.ToggleButton",
		 		"dijit.form.Button",
		 		"dijit.form._FormWidget",
		 		"dijit.form._FormWidgetMixin",
		 		"dijit.form._ButtonMixin",
		 		"dijit.form._ToggleButtonMixin",
		 		"dijit.layout.AccordionPane",
		 		"dijit.form._FormValueWidget",
		 		"dijit.form._FormValueMixin",
		 		"dijit.form.DropDownButton",
		 		"dijit._HasDropDown",
		 		"dijit.form.ComboButton",


		 		"dijit.layout.BorderContainer",
		 		"dijit.layout.ContentPane",
		 		"dojox.layout.ToggleSplitter",
		 		"dojox.layout.ContentPane",
		 		"dijit._Templated",
		 		"dijit._Widget",
		 		"dojo.cookie",
		 		"dojo.touch",
		 		"dijit._WidgetBase",
		 		"dijit._TemplatedMixin",
		 		"dijit.layout._LayoutWidget",
		 		"dijit.layout.utils",
		 		"dijit.main",
		 		"dojox.html._base",
		 		"dijit.layout._ContentPaneResizeMixin",
		 		"dojo.string",
		 		"dojo.html",
		 		"dijit.nls.loading",
		 		"dijit._WidgetsInTemplateMixin",
		 		"dojo.Stateful",
		 		"dijit.registry",
		 		"dojo.regexp",
		 		"dojo.cache",
		 		"dijit._OnDijitClickMixin",
		 		"dijit._FocusMixin",
		 		"dojo.uacss",
		 		"dijit.hccss",
		 		"dijit._Container",
		 		"dijit._Contained",
		 		"dojo._base.url",
		 		"dijit.nls.zh.loading",
		 		"dojo.parser",
		 		"dijit.layout.TabContainer",
		 		"dijit.Dialog",
		 		"dijit.form.Button",
		 		"dijit.focus",
		 		"dojo.date.stamp",
		 		"dijit.layout._TabContainerBase",
		 		"dijit.layout.TabController",
		 		"dijit.layout.ScrollingTabController",
		 		"dojox.image.LightboxNano",
		 		"dojox.image.MagnifierLite",
		 		"dojo.window",
		 		"dojo.dnd.Moveable",
		 		"dojo.dnd.TimedMoveable",
		 		"dijit._base.manager",
		 		"dijit._CssStateMixin",
		 		"dijit.form._FormMixin",
		 		"dijit._DialogMixin",
		 		"dijit.DialogUnderlay",
		 		"dijit.nls.common",
		 		"dijit.form._FormWidget",
		 		"dijit.form._ButtonMixin",
		 		"dijit.a11y",
		 		"dijit.layout.StackContainer",
		 		"dijit.layout.StackController",
		 		"dijit.Menu",
		 		"dijit.MenuItem",
		 		"dijit._HasDropDown",
		 		"dijit.BackgroundIframe",
		 		"dojo.dnd.Mover",
		 		"dijit.nls.zh.common",
		 		"dijit.form._FormWidgetMixin",
		 		"dojo.fx",
		 		"dijit.form.ToggleButton",
		 		"dijit.popup",
		 		"dijit.DropDownMenu",
		 		"dojo.dnd.common",
		 		"dojo.dnd.autoscroll",
		 		"dijit.form._ToggleButtonMixin",
		 		"dijit.place",
		 		"dijit._MenuBase",
		 		"dijit._KeyNavContainer",

		 		"dijit.form.FilteringSelect"
			]
		}
	],

	prefixes: [
		[ "dijit", "../dijit" ],
		[ "dojox", "../dojox" ]
	]
}
